services:
  - type: web
    name: lera-backend
    runtime: docker
    dockerfilePath: ./Dockerfile
    healthCheckPath: /api/v1/health
    envVars:
      - key: PORT
        value: 8080
      - key: SOCKETIO_PORT
        value: 9092
      - key: DDL_AUTO
        value: update
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_ACCESS_EXPIRATION_MS
        value: 900000
      - key: REFRESH_TOKEN_EXPIRATION_MS
        value: 604800000
      - key: DB_URL
        value: jdbc:postgresql://ep-bold-paper-a4253nug-pooler.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
      - key: DB_USERNAME
        value: neondb_owner
      - key: DB_PASSWORD
        value: npg_i8HJoyEI9nzZ
      - key: CORS_ORIGINS
        value: http://localhost:3000,http://localhost:3001,https://lera-frontend.vercel.app
      - key: FIREBASE_SERVICE_ACCOUNT_JSON
        value: ""
